name: SIO221A
channels:
  - defaults
  - conda-forge
dependencies:
  - netcdf4==1.5.7
  - pandas==1.3.2
  - xarray==0.19.0
  - matplotlib
  - libnetcdf==4.6.1
  - nc-time-axis==1.3.1
  - scipy==1.7.1
  - bokeh==2.3.3
  - datashader==0.13.0
  - holoviews==1.14.6
  - hvplot==0.7.3 
  - cartopy==0.20.0
  - jupyterlab==3.1.12
  - ipykernel==6.2.0
